"""Shared fixture loading and tolerance-policy helpers for MATLAB-vs-Python tests.

See `sttopt/conventions.md` for the array-order, fixture-format, and tolerance
conventions this module implements. Fixtures are `.mat` files generated by the MATLAB
harness (`tests/fixtures/generate_fixtures.m`) and committed under `tests/fixtures/`.
"""

from pathlib import Path

import numpy as np
import scipy.io

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def fixture_element_perm(nelx: int, nely: int) -> np.ndarray:
    """Maps a `.mat` fixture's 0-indexed element numbering (F-order/column-major, the
    frozen MATLAB convention) to `sttopt`'s 0-indexed element numbering (C-order/
    row-major -- see `sttopt/conventions.md`). `perm[e_fixture] == e_sttopt`.
    """
    e = np.arange(nelx * nely)
    i, j = e // nely, e % nely  # F-order decode: i = x-index, j = y-index
    return j * nelx + i  # C-order encode


def reindex_fixture(arr: np.ndarray, nelx: int, nely: int, axis: int = 0) -> np.ndarray:
    """Reindexes a fixture-derived array's element axis (length `nelx*nely`) from the
    fixture's F-order to `sttopt`'s C-order (`fixture_element_perm`), leaving any other
    axes untouched. For a matrix indexed by element on *both* axes (e.g. a filter
    matrix), call this once per axis.
    """
    perm = fixture_element_perm(nelx, nely)
    out = np.empty_like(arr)
    out.swapaxes(0, axis)[perm] = arr.swapaxes(0, axis)
    return out


def reindex_fixture_values(idx: np.ndarray, nelx: int, nely: int) -> np.ndarray:
    """Relabels a fixture-derived array of element *index values* (e.g. neighbor-pair
    `e1`/`e2` columns) from F-order to C-order -- as opposed to `reindex_fixture`,
    which reorders an array's element *axis* but leaves stored values unchanged.
    """
    return fixture_element_perm(nelx, nely)[idx]


def reindex_fixture_halves(
    arr: np.ndarray, nelx: int, nely: int, axis: int = 0
) -> np.ndarray:
    """`reindex_fixture`, for a raw-MMA-variable-shaped axis: `[x_half; t_half]`
    stacked along `axis`, each half element-indexed (length `nelx*nely`) and reindexed
    independently.
    """
    nel = nelx * nely
    swapped = arr.swapaxes(0, axis)
    x_half = reindex_fixture(swapped[:nel], nelx, nely, axis=0)
    t_half = reindex_fixture(swapped[nel:], nelx, nely, axis=0)
    return np.concatenate([x_half, t_half], axis=0).swapaxes(0, axis)


def load_fixture(name: str) -> dict:
    """Load a MATLAB-generated fixture by base filename (no `.mat` suffix).

    Returns a dict of numpy arrays as MATLAB saved them — 1-indexed element numbers
    where the source used 1-indexing (e.g. COO neighbor-list triplets), unconverted.
    Callers subtract 1 when comparing against Python's 0-indexed arrays.
    """
    return scipy.io.loadmat(
        FIXTURES_DIR / f"{name}.mat", squeeze_me=True, spmatrix=False
    )


def matlab_init_state(problem, beta: float):
    """The initial state the `.mat` fixtures were generated from: the reference's
    initialization, which leaves `xTilde` and `tPhys` unfiltered
    (`generate_fixtures.m:200-203`).

    `optimize.init_state` deliberately no longer reproduces this -- it derives both
    physics fields through the filter, since `step` differentiates `tPhys` as though
    `tPhys = H @ t / Hs` (PR #26). The committed `.mat` files are frozen artifacts of
    the old code and cannot be regenerated to match, so tests that compare against them
    enter the trajectory here instead, and keep checking what they were written to check
    -- the per-iteration agreement of `step`, not the seeding. `init_state`'s own
    behaviour is specified by `test_optimize.py`'s three init invariant tests.

    Unlike this helper, the live transliteration oracle (`matlab_reference_loop.py`)
    *does* follow the fix: it is code under our control, not a frozen artifact.
    """
    import sttopt.filters as filters
    import sttopt.optimize as optimize
    import sttopt.timefield as timefield

    x = np.full((problem.nely, problem.nelx), problem.volfrac)
    tPhys = timefield.init_timefield(problem.nelx, problem.nely, problem.tfield)
    nel = problem.nelx * problem.nely

    return optimize.State(
        x=x,
        xTilde=x.copy(),
        xPhys=filters.heaviside_projection(x.copy(), beta, problem.eta),
        t=tPhys.copy(),
        tPhys=tPhys,
        xold1=np.concatenate([x.flatten(), np.zeros(nel)]),
        xold2=np.concatenate([x.flatten(), np.zeros(nel)]),
        low=np.zeros(problem.n),
        upp=np.zeros(problem.n),
        loop=0,
        rou=10.0,
        beta=beta,
        factor=1.0,
    )


def load_fixture_npz(name: str) -> dict:
    """Load a Python-generated (non-MATLAB) fixture by base filename (no `.npz` suffix).

    For regression fixtures with no MATLAB counterpart -- e.g. golden values frozen from
    a Python scene the source MATLAB code never modeled -- 0-indexed throughout.
    """
    with np.load(FIXTURES_DIR / f"{name}.npz") as data:
        return dict(data)


def e2e_rtol(
    iteration: int, *, base_rtol: float = 1e-9, max_rtol: float = 1e-2
) -> float:
    """Relative tolerance for an end-to-end trajectory comparison at a given loop iteration.

    `subsolv`'s inner Newton line search amplifies small per-iteration differences, so
    exact agreement isn't realistic after many MMA iterations. Tolerance grows
    geometrically with iteration count (one decade looser per iteration by default),
    capped at `max_rtol`; tune `base_rtol`/`max_rtol` per test if this default doesn't
    match observed behavior.
    """
    return min(max_rtol, base_rtol * 10 ** (iteration - 1))


def assert_close(
    actual,
    expected,
    *,
    tier: str = "algebraic",
    iteration: int | None = None,
    atol: float = 1e-12,
):
    """Compare a ported quantity to its MATLAB fixture value, per the tolerance policy.

    tier:
      - "algebraic": purely algebraic, no linear solve involved (rtol=1e-10) — filters,
        neighbor weights, KE.
      - "solved": downstream of a sparse linear solve (rtol=1e-6) — U, compliance and
        its sensitivities.
      - "e2e": end-to-end trajectory comparison; pass `iteration` to scale tolerance
        via `e2e_rtol`.
    """
    tier_rtol = {"algebraic": 1e-10, "solved": 1e-6}
    if tier == "e2e":
        if iteration is None:
            raise ValueError("tier='e2e' requires `iteration`")
        rtol = e2e_rtol(iteration)
    else:
        rtol = tier_rtol[tier]
    np.testing.assert_allclose(
        np.asarray(actual), np.asarray(expected), rtol=rtol, atol=atol
    )
