"""Shared fixture-loading and tolerance-policy helpers.

Fixtures under `tests/fixtures/*.npz` are golden-regression snapshots generated by
`tests/fixtures/generate_fixtures.py` from the current `sttopt` code itself -- they
catch unintended future changes to that output, not correctness against an
independent implementation (see `sttopt/conventions.md`). The one exception is
`matlab_reference_dof_perm`/`matlab_reference_node_perm` below, which stay in the
*other* direction on purpose: `tests/matlab_reference.py`/`matlab_reference_loop.py`
are a from-scratch transliteration of the original MATLAB source, kept in its native
1-indexed, F-order (column-major) convention as an independent correctness oracle
(`test_reference_sweep.py`), and these two helpers relabel *that* oracle's output into
`sttopt`'s 0-indexed, C-order convention for comparison.
"""

import dataclasses
import json
from pathlib import Path

import numpy as np
import torch

import sttopt.fem as fem
from sttopt.run_config import RunConfig


def _as_numpy(x) -> np.ndarray:
    """Coerce a tensor, NumPy array, or scalar to a NumPy array, detaching/moving a
    tensor to host first so a GPU or autograd-tracked value doesn't error `np.asarray`.
    """
    if isinstance(x, torch.Tensor):
        return x.detach().cpu().numpy()
    return np.asarray(x)


def tt(x, dtype: torch.dtype = torch.float64) -> torch.Tensor:
    """Convert a NumPy array (or other array-like) to a CPU tensor, for tests that
    build plain-NumPy inputs to feed the (now torch) leaf math in `sttopt`.
    """
    return torch.as_tensor(np.asarray(x), dtype=dtype)


def tti(x) -> torch.Tensor:
    """`tt`, for integer index/mask arrays (`edofMat`, `freedofs`, ...)."""
    return tt(x, dtype=torch.int64)


FIXTURES_DIR = Path(__file__).parent / "fixtures"
DEFAULT_CONFIG_PATH = Path(__file__).parent.parent / "configs" / "default.json"


def default_run_config(**overrides) -> RunConfig:
    """`RunConfig` loaded from `configs/default.json` (the single source of default
    hyperparameters) with `overrides` applied -- for tests/benchmarks that only care
    about a handful of fields (typically mesh size) and want everything else at the
    production default.
    """
    base = RunConfig.from_dict(json.loads(DEFAULT_CONFIG_PATH.read_text()))
    return dataclasses.replace(base, **overrides)


def matlab_reference_node_perm(nelx: int, nely: int) -> np.ndarray:
    """Maps `matlab_reference.py`'s 0-indexed node numbering (F-order/column-major, the
    original MATLAB convention) to `sttopt`'s 0-indexed node numbering (C-order/
    row-major -- see `sttopt/conventions.md`). `perm[n_reference] == n_sttopt`.
    """
    n = np.arange((nelx + 1) * (nely + 1))
    c, r = n // (nely + 1), n % (nely + 1)  # F-order decode
    return fem.node_grid(nelx, nely)[r, c]


def matlab_reference_dof_perm(nelx: int, nely: int) -> np.ndarray:
    """`matlab_reference_node_perm`, lifted to dofs: each node `n` owns the interleaved
    `(x, y)` pair `2n`, `2n+1`, so a dof keeps its component and follows its node.
    """
    node_perm = matlab_reference_node_perm(nelx, nely)
    return np.stack([2 * node_perm, 2 * node_perm + 1], axis=-1).ravel()


def node_positions(nelx: int, nely: int) -> tuple[np.ndarray, np.ndarray]:
    """Inverse of `fem.node_grid`: the `(row, col)` grid position of every node, as two
    arrays indexed by global node number. Lets a test that knows a node's mesh position
    state an expectation per dof without re-deriving the numbering formula.
    """
    nodes = fem.node_grid(nelx, nely)
    rows, cols = np.indices(nodes.shape)
    row_of = np.empty(nodes.size, int)
    col_of = np.empty(nodes.size, int)
    row_of[nodes.ravel()] = rows.ravel()
    col_of[nodes.ravel()] = cols.ravel()
    return row_of, col_of


def point_load_problem(nelx: int, nely: int) -> tuple[np.ndarray, np.ndarray, int]:
    """`(F, freedofs, ndof)` for the fixed cantilever load case the fixtures were
    generated under: unit downward point load on the bottom-right node, left edge
    clamped in both directions. This is the geometry MATLAB's `F(2*(nelx+1)*(nely+1))
    = -1` / `fixeddofs = 1:2*(nely+1)` denote; keeping it here rather than restating
    those formulas per test file keeps it in step with `optimize.build_problem`.
    """
    nodes = fem.node_grid(nelx, nely)
    ndof = 2 * nodes.size
    F = np.zeros(ndof)
    F[2 * nodes[-1, -1] + 1] = -1.0
    left_edge = nodes[:, 0]
    fixeddofs = np.stack([2 * left_edge, 2 * left_edge + 1], axis=-1).ravel()
    return F, np.setdiff1d(np.arange(ndof), fixeddofs), ndof


def reindex_matlab_reference_nodes(
    arr: np.ndarray, nelx: int, nely: int, axis: int = 0
) -> np.ndarray:
    """Reindexes a `matlab_reference.py`-derived array's node axis (length
    `(nelx+1)*(nely+1)`) from its F-order to `sttopt`'s C-order
    (`matlab_reference_node_perm`), leaving any other axes untouched.
    """
    perm = matlab_reference_node_perm(nelx, nely)
    out = np.empty_like(arr)
    out.swapaxes(0, axis)[perm] = arr.swapaxes(0, axis)
    return out


def load_fixture_npz(name: str) -> dict:
    """Load a golden-regression fixture (generated by
    `tests/fixtures/generate_fixtures.py`) by base filename (no `.npz` suffix).
    0-indexed, C-order throughout -- matches `sttopt`'s own conventions directly, no
    relabeling needed.
    """
    with np.load(FIXTURES_DIR / f"{name}.npz") as data:
        return dict(data)


def e2e_rtol(
    iteration: int, *, base_rtol: float = 1e-9, max_rtol: float = 1e-2
) -> float:
    """Relative tolerance for an end-to-end trajectory comparison at a given loop iteration.

    `subsolv`'s inner Newton line search amplifies small per-iteration differences, so
    exact agreement isn't realistic after many MMA iterations. Tolerance grows
    geometrically with iteration count (one decade looser per iteration by default),
    capped at `max_rtol`; tune `base_rtol`/`max_rtol` per test if this default doesn't
    match observed behavior.
    """
    return min(max_rtol, base_rtol * 10 ** (iteration - 1))


def assert_close(
    actual,
    expected,
    *,
    tier: str = "algebraic",
    iteration: int | None = None,
    atol: float = 1e-12,
):
    """Compare a ported quantity to its MATLAB fixture value, per the tolerance policy.

    tier:
      - "algebraic": purely algebraic, no linear solve involved (rtol=1e-10) — filters,
        neighbor weights, KE.
      - "solved": downstream of a sparse linear solve (rtol=1e-6) — U, compliance and
        its sensitivities.
      - "e2e": end-to-end trajectory comparison; pass `iteration` to scale tolerance
        via `e2e_rtol`.
    """
    tier_rtol = {"algebraic": 1e-10, "solved": 1e-6}
    if tier == "e2e":
        if iteration is None:
            raise ValueError("tier='e2e' requires `iteration`")
        rtol = e2e_rtol(iteration)
    else:
        rtol = tier_rtol[tier]
    np.testing.assert_allclose(
        _as_numpy(actual), _as_numpy(expected), rtol=rtol, atol=atol
    )
