"""Shared fixture loading and tolerance-policy helpers for MATLAB-vs-Python tests.

See `sttopt/conventions.md` for the array-order, fixture-format, and tolerance
conventions this module implements. Fixtures are `.mat` files generated by the MATLAB
harness (`tests/fixtures/generate_fixtures.m`) and committed under `tests/fixtures/`.
"""

from pathlib import Path

import numpy as np
import scipy.io

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def load_fixture(name: str) -> dict:
    """Load a MATLAB-generated fixture by base filename (no `.mat` suffix).

    Returns a dict of numpy arrays as MATLAB saved them — 1-indexed element numbers
    where the source used 1-indexing (e.g. COO neighbor-list triplets), unconverted.
    Callers subtract 1 when comparing against Python's 0-indexed arrays.
    """
    return scipy.io.loadmat(FIXTURES_DIR / f"{name}.mat", squeeze_me=True)


def e2e_rtol(
    iteration: int, *, base_rtol: float = 1e-9, max_rtol: float = 1e-2
) -> float:
    """Relative tolerance for an end-to-end trajectory comparison at a given loop iteration.

    `subsolv`'s inner Newton line search amplifies small per-iteration differences, so
    exact agreement isn't realistic after many MMA iterations. Tolerance grows
    geometrically with iteration count (one decade looser per iteration by default),
    capped at `max_rtol`; tune `base_rtol`/`max_rtol` per test if this default doesn't
    match observed behavior.
    """
    return min(max_rtol, base_rtol * 10 ** (iteration - 1))


def assert_close(
    actual,
    expected,
    *,
    tier: str = "algebraic",
    iteration: int | None = None,
    atol: float = 1e-12,
):
    """Compare a ported quantity to its MATLAB fixture value, per the tolerance policy.

    tier:
      - "algebraic": purely algebraic, no linear solve involved (rtol=1e-10) — filters,
        neighbor weights, KE.
      - "solved": downstream of a sparse linear solve (rtol=1e-6) — U, compliance and
        its sensitivities.
      - "e2e": end-to-end trajectory comparison; pass `iteration` to scale tolerance
        via `e2e_rtol`.
    """
    tier_rtol = {"algebraic": 1e-10, "solved": 1e-6}
    if tier == "e2e":
        if iteration is None:
            raise ValueError("tier='e2e' requires `iteration`")
        rtol = e2e_rtol(iteration)
    else:
        rtol = tier_rtol[tier]
    np.testing.assert_allclose(
        np.asarray(actual), np.asarray(expected), rtol=rtol, atol=atol
    )
